title: ETS
description: Standardize the input given by the state of Hawai‘i's independent verification and validation (IV&V) vendors
show_downloads: false
theme: jekyll-theme-cayman
github:
    is_project_page: true
    repository_url: https://github.com/oh-yeah-ics-314-final-project-7-lets-go/oh-yeah-ics-314-final-project-7-lets-go.github.io
